import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "@/components/nav/aside";
import Logo from "@/components/nav/logo";
import Tabs from "@/components/nav/tabs";
import AsideFooter from "@/components/nav/aside-footer";
import TopNav from "@/components/nav/top-nav";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Keep it simple
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full`} suppressHydrationWarning>
      {/* h-full here is critical to ensure the body can fill the screen */}

      <body
        className={`${inter.className}  h-full flex flex-col md:flex-row antialiased w-full`}
      >
        {/* 1. ASIDE: Fixed width, glass style, stays on the left */}
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="hidden md:flex flex-col w-64 h-full glass border-r border-brand-100/20 dark:bg-stone-800">
              <div className="bg-white dark:bg-stone-800">
                <Logo />
              </div>
              <hr className="slate-300" />
              <Aside className="flex-1" />
              <AsideFooter />
            </div>
            {/* MOBILE TABS: Only visible on small screens (below md) */}

            <main className="bg-brand-100/50 dark:bg-black flex-1 h-full overflow-y-auto flex flex-col">
              <TopNav />
              <div className="p-8 flex-1">{children}</div>
            </main>

            <div className="md:hidden w-full">
              <Tabs />
            </div>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
